### ISSUE TITLE
Как можно реализовать принятие сообщение в реальном времени?

### ISSUE THREAD

**Issue by iamRuda** [Aragroth/vk_messages#2]
Спасибо вам большое за данный открытый проект! :) Возникла такая проблема, нужно принимать сообщения в реальном времени, и мгновенно на них отвечать, а также принимать сообщения свои и чужие в реальном времени. Возможно ли такое осуществить с помощью вашего проекта? Заранее спасибо

**Comment by Aragroth** [comment]
Можно использовать метод messages.getConversations с ключом unread, чтобы всегда получать только диалоги с непрочитанными сообщениями и проходится по списку этих айди методом messages.getHistory и делать какую-то логику. После этого просто помечать диалоги как прочитанные через messages.markAsRead. Все методы описаны в официальной документации:


Такое лучше реализовывать посредством ботов сообществ.

Можно выбрать между Longpool или Callback:
https://vk.com/dev/bots_docs
https://vk.com/dev/bots_docs?f=2.2.%20Bots%20Long%20Poll%20API
https://github.com/python273/vk_api/blob/master/examples/bot_longpoll.py

**Comment by Aragroth** [comment]
Можно использовать метод messages.getConversations с ключом unread, чтобы всегда получать только диалоги с непрочитанными сообщениями и проходится по списку этих айди методом messages.getHistory и делать какую-то логику. После этого просто помечать диалоги как прочитанные через messages.markAsRead. Все методы описаны в [официальной документации](https://vk.com/dev/messages).

Но такого лучше не делать, потому что пользователи должны быть по политике ВК реальными людьми. Такое лучше реализовывать посредством ботов сообществ. Можно выбрать между [Longpool или Callback](https://vk.com/dev/bots_docs).

[Отличная Python библиотека для реализации ботов сообществ с примерами.](https://github.com/python273/vk_api/blob/master/examples/bot_longpoll.py)

**Comment by RudFireMan** [comment]
Вы правы, все методы описаны в официальной документации, но я не понимаю,
как это на фото, можно преобразовать в Python. Если вам будет несложно,
можете дать краткий гайд "Как с помощью вашей библиотеки, можно осуществить
ту или иную функцию, если ты с ней незнаком". Очень интересен метод чтения
последнего сообщения собеседника, и последнего сообщения, которое пришло от
тебя. Потому что в Python, я почти полнейший ноль, я специализируюсь на
C++, и я никогда не писал ботов.
Поймите, я никакого злого умысла не имею, мне не нужно создать бота который
бы воровал информацию с других пользователей. Я делаю школьный проект по
искусственному интеллекту основанный на алгоритмах.  Сам интеллект уже
готов, написан на С++, и он в рабочем состояние. Я уже знаю, как я буду
интегрировать с Python. Но искусственному интеллекту нужно учиться. И
поэтому мне нужно сделать бота который бы читал сообщения собеседника и
свои(то есть сообщения хозяина страницы, с которой он сидит) в реальном
времени. Вы направьте меня, напишите, как должен выглядеть кусок кода,
который позволит выполнять данные задачи. Логику я сам построю, это будет
нетрудно. Если вы сделаете это, тысячу вам спасибо 😃

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 19 апр. 2020 г. в 17:11, Aragroth <notifications@github.com>:

**Comment by RudFireMan** [comment]
Прикрепляю фото

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
