### ISSUE TITLE
Update in pip?

### ISSUE THREAD

**Issue by istudyatuni** [Aragroth/vk_messages#4]
В pip видимо до сих пор ANSI:
```
    self.password = str(password.encode('ANSI')).replace('\\x', '%')[2:-1]
LookupError: unknown encoding: ANSI
```

**Comment by istudyatuni** [comment]
![screenshot](https://user-images.githubusercontent.com/43654815/104806534-3d289b80-57e9-11eb-9a0f-94594cf943de.png)

**Comment by Maze21127** [comment]
По каким-то причинам с двухфакторной ничего не работает, получаю ошибку 
vk_messages.vk_messages.Exception_MessagesAPI: Invalid login data or wrong auth method
Хотя данные ввожу верные, two_factor=True стоит

**Comment by istudyatuni** [comment]
Как вариант может быть что-то поменялось в том, что приходит от вк

**Comment by MagicWinnie** [comment]
> Как вариант может быть что-то поменялось в том, что приходит от вк

Замените в файле `vk_messages.py` 96-ю строку на `hash_url =  re.findall(r"Authcheck\.init\('([a-z_0-9]+)'", str(response.text))`

**Comment by MagicWinnie** [comment]
> По каким-то причинам с двухфакторной ничего не работает, получаю ошибку
> vk_messages.vk_messages.Exception_MessagesAPI: Invalid login data or wrong auth method
> Хотя данные ввожу верные, two_factor=True стоит

> Как вариант может быть что-то поменялось в том, что приходит от вк

Можно заменить в файле `vk_messages.py` 96-ю строку на `hash_url =  re.findall(r"Authcheck\.init\('([a-z_0-9]+)'", str(response.text))`  
Взял регулярное выражение из либы `vk_api`

**Comment by Aragroth** [comment]
> Можно заменить в файле `vk_messages.py` 96-ю строку на `hash_url = re.findall(r"Authcheck\.init\('([a-z_0-9]+)'", str(response.text))`

Добавил изменения, подтверждаю что работает. Залил новую версию пакета на pypi
