### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MoonSer** [Aragroth/vk_messages#8]
В душе не *бу что происходит, но последнюю неделю постоянно сыпется ошибка 
"vk_messages.vk_messages.Exception_MessagesAPI: Rate limit reached"
Вроде она из-за слишком большого количества запросов, но я попробовал отправить что-то на другом аккаунте, для которого АПИ не использую, и всё равно (
По IP что ли бан 0_0?
Да и насколько знаю, есть лимиты для каждого метода на вызов в сутки, а тут в любом случае вылетает последнюю неделю...
Example:
```
from vk_messages import MessagesAPI
from vk_messages.utils import get_random
login, password = "X", "Y"
peer_id = "1"
messages = MessagesAPI(login=login, password=password, two_factor=False)
messages.method('messages.send', user_id=peer_id, message='Hello', random_id=get_random())
```

Out:

```
'raise Exception_MessagesAPI(json.loads(response_json[1][0])['error']['error_msg'],
vk_messages.vk_messages.Exception_MessagesAPI: Rate limit reached'
```
Помогите пожалуйста разобраться, мб кто-то сталкивался?

**Comment by Malkiz223** [comment]
Проблема вряд ли связана с IP и каким-то баном по нему. Полгода назад мой скрипт успешно работал. 
В течение полугода я не использовал API VK, но сейчас решил обновить зависимости и проверить работоспособность. Получаю такую же ошибку.

**Comment by Malkiz223** [comment]
Ситуацию исправил переход на https://pypi.org/project/vk-api/
Пришлось немного поковыряться. При создании экземпляра сессии передал аргумент app_id=6121396 - приложение VK Admin, либо номер приложения Kate Mobile: 2685278. Ещё изменил api_version='5.131'.
api_version менять не обязательно, просто мой старый код начал выдавать ошибки из-за смены версии API.
У данной библиотеки использован API v5.103, так что если раньше всё работало с ним, можно указать эту версию.

Ещё из изменений в коде пришлось передавать аргументы метода VK API в виде словаря:
vk_session.method('messages.getHistory', values={'user_id': self.friend_id})

**Comment by MoonSer** [comment]
![image](https://user-images.githubusercontent.com/44445889/133194419-34544d7a-5bc0-4fec-8e36-92eb1d706544.png)
Прст у меня на официальном сайте ВК такая же шляпа(
Поэтому подумал про бан.

В библиотеке vk-api по-моему нельзя было отправлять сообщения, но возможно это было из-за app_id. Спасибо большое)
